name: Ambrosia Varaschin Photography
favicon: null
layout_spectrum: 0.50298
typography_spectrum: 0.99925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f4fdfc'
    - '#aaaaaa'
    - '#757979'
    - '#d3d3d3'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
